### ISSUE TITLE
出现 AttributeError: 'dict' object has no attribute 'sleep'

### ISSUE THREAD

**Issue by Kuoliang-Chung** [kajweb/wqxuetang_downloader#13]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    book.start( *(int(x) for x in sys.argv[2:]) );
  File "C:\Users\8366\Desktop\wqxuetang_downloader-master\wqxtDownloader.py", line 172, in start
    time.sleep( self.errorConfig.sleep )
AttributeError: 'dict' object has no attribute 'sleep'

**Comment by kajweb** [comment]
稍等，我看下

**Comment by kajweb** [comment]
已修复，感谢您的提醒。

**Comment by kajweb** [comment]
麻烦pull后再试。

**Comment by Kuoliang-Chung** [comment]
> 麻烦pull后再试。

太敬业了！感谢您！
