### ISSUE TITLE
HTTP Error 502

### ISSUE THREAD

**Issue by Kuoliang-Chung** [kajweb/wqxuetang_downloader#22]
能否增加个出现 HTTP Error 502 的时候，自动重启的功能？
————————————————————————————————————————————
错误如下：
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    book = wqxtDownloader( bid );
  File "C:\Users\83669\Desktop\wqxuetang_downloader-master (1)\wqxuetang_downloader-master\wqxtDownloader.py", line 36, in __init__
    self.catatree = self.getCatatree();
  File "C:\Users\83669\Desktop\wqxuetang_downloader-master (1)\wqxuetang_downloader-master\wqxtDownloader.py", line 84, in getCatatree
    request  = curl.request.urlopen(url);
  File "C:\Users\83669\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\83669\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\83669\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\83669\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\83669\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\83669\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

**Comment by TheGayhub** [comment]
我感觉这个用的人太多了，顶不住了，我一张也下载不了了

**Comment by Kuoliang-Chung** [comment]
> 我感觉这个用的人太多了，顶不住了，我一张也下载不了了
什么东西都会被玩坏呀。。。
清华大学出版社的这个文泉学堂，设计的时候就应该不能承受得了这么高的并发吧。
我还是新闻上第一次看到这个数据库，以前没了解过。

**Comment by 1990chs** [comment]
我也出现这种问题了

**Comment by kdxcxs** [comment]
我用我自己的代码也下不了了……现在网页打开就一直加载，加了代理都不行，应该是服务器不行了

**Comment by iMicroSoftever** [comment]
CMD关了重试就行了。再失败再重试。
