### ISSUE TITLE
获取到了失败的图片

### ISSUE THREAD

**Issue by 1990chs** [kajweb/wqxuetang_downloader#25]
2020-02-04 17:33:43,378 [ERROR] 3209066 获取到了失败的图片 第366页(366/417) 正在重试第1次
2020-02-04 17:33:48,795 [ERROR] 3209066 获取到了失败的图片 第366页(366/417) 正在重试第2次
2020-02-04 17:33:57,981 [ERROR] 3209066 获取到了失败的图片 第366页(366/417) 正在重试第3次
2020-02-04 17:34:05,145 [ERROR] 3209066 获取到了失败的图片 第366页(366/417) 正在重试第4次
2020-02-04 17:34:13,447 [ERROR] 3209066 获取到了失败的图片 第366页(366/417) 正在重试第5次
2020-02-04 17:34:28,017 [ERROR] 3209066 获取到了失败的图片 第366页(366/417) 正在重试第6次
2020-02-04 17:34:37,791 [CRITICAL] 重试次数过多，程序终止，请尝试重新执行main.py
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    book.start( *(int(x) for x in sys.argv[2:]) );
  File "G:\文泉下载\wqxuetang_downloader-master\wqxtDownloader.py", line 176, in start
    raise TooManyRetry;
wqxtDownloader.TooManyRetry

**Comment by kajweb** [comment]
IP检测被封了。
现在需要登录，所以暂时停止更新。
