### ISSUE TITLE
使用前一版本，按补丁1和2都修改了，但出现这个错请问怎么解决：list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by ynlsg** [kajweb/wqxuetang_downloader#39]
C:\Users\ynlsg\wqxuetang_downloader10>python main.py 3208995 83 388
C:\Users\ynlsg\wqxuetang_downloader10\cookies.txt
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    book = wqxtDownloader( bid );
  File "C:\Users\ynlsg\wqxuetang_downloader10\wqxtDownloader.py", line 32, in __init__
    self.name = bookInfo['name'];
TypeError: list indices must be integers or slices, not str

**Comment by ynlsg** [comment]
看前面的问题解决，感谢kajweb大佬~~
