### ISSUE TITLE
我这个报错

### ISSUE THREAD

**Issue by TheGayhub** [kajweb/wqxuetang_downloader#4]
错误如下
```python
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from wqxtDownloader import *;
  File "D:\Other\wqxuetang_downloader-master\wqxtDownloader.py", line 5, in <module>
    from wqxtPDF import *
  File "D:\Other\wqxuetang_downloader-master\wqxtPDF.py", line 8, in <module>
    import fitz # pip3 install pymupdf
ModuleNotFoundError: No module named 'fitz'
```

**Comment by litengde** [comment]
不是写着让你安装这个库了嘛# pip3 install pymupdf
啊哈哈哈

**Comment by TheGayhub** [comment]
> 不是写着让你安装这个库了嘛# pip3 install pymupdf
> 啊哈哈哈

不好意思啊，我是小白，没弄过这个，也几乎不懂python

**Comment by TheGayhub** [comment]
> 不是写着让你安装这个库了嘛# pip3 install pymupdf
> 啊哈哈哈

谢谢你，执行这个命令后就好了

**Comment by kajweb** [comment]
我这边跑不动了

**Comment by kajweb** [comment]
执行 `pip3 install pymupdf` 安装依赖即可。
