### ISSUE TITLE
“套接字操作尝试一个无法连接的主机的”错误

### ISSUE THREAD

**Issue by Kuoliang-Chung** [kajweb/wqxuetang_downloader#41]
出现了这种问题，目前重启就行了
————————————————————————————————————————————
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    book.start( *(int(x) for x in sys.argv[2:]) );
  File "C:\Users\83669\Desktop\wqxuetang_downloader-master\wqxtDownloader.py", line 158, in start
    downloadPage = self.downloadImage( url, path );
  File "C:\Users\83669\Desktop\wqxuetang_downloader-master\wqxtDownloader.py", line 217, in downloadImage
    request = curl.request.urlopen(requestPer, timeout=10);
  File "C:\Users\83669\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\83669\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\83669\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\83669\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\83669\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\83669\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10065] 套接字操作尝试一个无法连接的主机。>

**Comment by kajweb** [comment]
patch2打了没？
也可能是你频率太快被banIP。
