### ISSUE TITLE
main.py 单个下载正常 / main_mult.py 多个下载报错

### ISSUE THREAD

**Issue by Doueast** [kajweb/wqxuetang_downloader#51]
请输入需要下载的bid(以间隔)：3208944 3207422
2020-02-06 16:54:01,233 [INFO] 成功创建文件夹 books/IMG/3208944
············
2020-02-06 17:11:52,414 [INFO] 3208944下载成功 第56页(56/211) 随机11.7s
Traceback (most recent call last):
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "e:\Personal\Desktop\wqxuetang_downloader-master\main_mult.py", line 29, in <module>
    parseMultBid( Abid );
  File "e:\Personal\Desktop\wqxuetang_downloader-master\main_mult.py", line 19, in parseMultBid
    book.start();
  File "e:\Personal\Desktop\wqxuetang_downloader-master\wqxtDownloader.py", line 163, in start
    downloadPage = self.downloadImage( url, path );
  File "e:\Personal\Desktop\wqxuetang_downloader-master\wqxtDownloader.py", line 224, in downloadImage
    request = curl.request.urlopen(requestPer, timeout=10);
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1323, in do_open
    r = h.getresponse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
PS E:\Personal\Desktop\wqxuetang_downloader-master>

**Comment by BillXuce** [comment]
尽量还是使用单个文件下载的方式吧，这个错误原因是远程将连接关闭了，即使是单个文件下载的脚本也有很多中途被关闭连接的情况，这种情况还是需要自己手工重新运行脚本。总体还是推荐单个文件的下载方式

**Comment by kajweb** [comment]
> 尽量还是使用单个文件下载的方式吧，这个错误原因是远程将连接关闭了，即使是单个文件下载的脚本也有很多中途被关闭连接的情况，这种情况还是需要自己手工重新运行脚本。总体还是推荐单个文件的下载方式

我用`main_mult.py`还是挺稳定的，可能我调的比较慢吧
