### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by zhuting233** [kajweb/wqxuetang_downloader#58]
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    book.start([]);
  File "C:\Users\zhuqi\Downloads\wqxuetang_downloader-master\wqxtDownloader.py", line 162, in start
    downloadPage = self.downloadImage( url, path );
  File "C:\Users\zhuqi\Downloads\wqxuetang_downloader-master\wqxtDownloader.py", line 223, in downloadImage
    request = curl.request.urlopen(requestPer, timeout=10);
  File "E:\Dev\Anaconda\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Dev\Anaconda\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "E:\Dev\Anaconda\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "E:\Dev\Anaconda\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "E:\Dev\Anaconda\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "E:\Dev\Anaconda\lib\urllib\request.py", line 1320, in do_open
    r = h.getresponse()
  File "E:\Dev\Anaconda\lib\http\client.py", line 1336, in getresponse
    response.begin()
  File "E:\Dev\Anaconda\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "E:\Dev\Anaconda\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by zhuting233** [comment]
过了一会然后可以了...
