### ISSUE TITLE
netscape.javascript.JSException: ReferenceError: Can't find variable: getNVCVal

### ISSUE THREAD

**Issue by odd2008** [kajweb/wqxuetang_downloader#73]
mac环境最新的代码
`[INFO ] 2020-02-10 23:59:03 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - oldState:RUNNING -> newState:SUCCEEDED
netscape.javascript.JSException: ReferenceError: Can't find variable: getNVCVal
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
	at com.sun.webkit.dom.JSObject.evalImpl(Native Method)
	at com.sun.webkit.dom.JSObject.eval(JSObject.java:52)
	at online.githuboy.wqxuetang.pdfd.ui.WebContainer.getNVC(WebContainer.java:55)
	at online.githuboy.wqxuetang.pdfd.ui.WebContainer.lambda$initEngine$2(WebContainer.java:72)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1260)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1371)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1253)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1240)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2400)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2244)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:838)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$96(URLLoader.java:829)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
[ERROR] 2020-02-10 23:59:18 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 程序初始化失败
Disconnected from the target VM, address: '127.0.0.1:51562', transport: 'socket'`

**Comment by BillXuce** [comment]
issue交错项目了
